openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost
  description: Generated server url
paths:
  /sample:
    get:
      tags:
      - sample-rest-controller
      summary: サンプルレスポンス返却
      description: サンプルレスポンスを返却します
      operationId: getResponse
      responses:
        "200":
          description: 正常
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SampleResponse'
components:
  schemas:
    SampleResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
